<template>
	<main class="wiki-highlight-categories">
		<div
			v-for="( articles, category ) in categories"
			:key="category"
		>
			<h2>{{ category }}</h2>
			<HighlightThumb
				v-for="article in articles"
				:key="article.title"
				:image="source === 'highlights' ? article.highlights[0].image : article.leadImage"
				:title="article.title"
				:text="source === 'highlights' ? article.highlights[0].text : article.summary"
				:source="source"
			/>
		</div>
		<p v-if="source === 'highlights'" class="wiki-highlight-categories-license">
			The text has been generated by an LLM, adapted from Wikipedia, and is based on <a rel="nofollow" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">CC BY-SA 4.0</a> licensed material.
		</p>
		<p v-else class="wiki-highlight-categories-license">
			Content is available under <a rel="nofollow" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">CC BY-SA 4.0</a>, unless otherwise noted.
		</p>
	</main>
</template>

<script setup>
import HighlightThumb from '../components/HighlightThumb.vue';
import { categories } from '../data.js';
defineProps( {
	source: { type: String, required: true }
} );
</script>

<style>
.wiki-highlight-categories {
	padding: 10px 0 10px 20px;
}

.wiki-highlight-categories-license {
	margin-right: 10px;
}
</style>
