<template>
	<main class="wiki-highlight-categories">
		<div
			v-for="( articles, category ) in categories"
			:key="category"
			class="wiki-highlight-category"
		>
			<h2>{{ category }}</h2>
			<div class="wiki-highlight-thumb-container">
				<HighlightThumb
					v-for="article in articles"
					:key="article.title"
					:image="source === 'highlights' ? article.highlights[0].image : article.leadImage"
					:title="article.title"
					:text="source === 'highlights' ? article.highlights[0].text : article.summary"
					:source="source"
				/>
			</div>
		</div>
	</main>
	<p class="wiki-highlight-categories-license">
		<span v-if="source === 'highlights'">The text has been generated by an LLM, adapted from Wikipedia, and is based on <a rel="nofollow" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">CC BY-SA 4.0</a> licensed material.</span>
		<span v-else>Content is available under <a rel="nofollow" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">CC BY-SA 4.0</a>, unless otherwise noted.</span>
		<br>
		<a rel="nofollow" href="https://wikimediafoundation.org/privacy-policy/">Wikimedia Foundation Non-wiki Privacy Policy</a> | <a rel="nofollow" href="https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement">Github Privacy Statement</a> | <a rel="nofollow" href="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service">Github Terms of Service</a>
	</p>
</template>

<script setup>
import HighlightThumb from '../components/HighlightThumb.vue';
import { categories } from '../data.js';
defineProps( {
	source: { type: String, required: true }
} );
</script>

<style>
.wiki-highlight-categories {
	padding: 10px 0 10px 16px;
}

.wiki-highlight-category {
	margin-bottom: 16px;
}

.wiki-highlight-category > h2 {
	font-size: 1.4em;
	font-weight: normal;
	color: #000;
	letter-spacing: 0.05em;
	font-family: 'Linux Libertine', 'Georgia', 'Times', 'Source Serif Pro', serif;
	text-transform: lowercase;
}

.wiki-highlight-category > h2::first-letter {
	text-transform: uppercase;
}

.wiki-highlight-categories-license {
	font-size: 0.8em;
	background-color: #f8f9fa;
	color: #54595d;
	padding: 16px;
}

.wiki-highlight-categories-license a {
	color: #36c;
}

.wiki-highlight-thumb-container {
	display: flex;
	flex-wrap: wrap;
}

@media ( prefers-color-scheme: dark ) {
	.wiki-highlight-category > h2 {
		color: #eaecf0;
	}

	.wiki-highlight-categories-license {
		background-color: unset;
		color: unset;

		a {
			color: #69F;
		}
	}
}
</style>
